%GENERATE_POTENTIAL_SPLITTING_TIME_TO_TARGET Export paper table data.
%
% This postprocessor reads the completed fixed-budget splitting archive.
% It never reruns a solver and uses the first accepted iterate satisfying
% each projected-gradient threshold (no interpolation).

projectRoot = fileparts(fileparts(mfilename('fullpath')));
repositoryRoot = fileparts(projectRoot);
resultFile = fullfile(projectRoot, 'results', ...
    'potential_splitting_sigma_comparison.mat');
tableFolder = fullfile(repositoryRoot, 'manuscript', 'tables');
rowsFile = fullfile(tableFolder, ...
    'potential_splitting_comparison_rows.tex');
tableFile = fullfile(tableFolder, ...
    'potential_splitting_comparison_table.tex');
csvFile = fullfile(projectRoot, 'results', ...
    'potential_splitting_time_to_target.csv');

assert(isfile(resultFile), ...
    'The completed potential-splitting comparison archive is missing.');
if ~isfolder(tableFolder), mkdir(tableFolder); end

data = load(resultFile);
required = {'signature', 'rho0', 'objectiveChecks', 'records', ...
    'checkpointFile'};
assert(all(isfield(data, required)), ...
    'The potential-splitting archive is incomplete.');

sigmaList = [1e-4, 1e-6];
thresholds = [1e-4, 1e-5, 1e-6];
splittingNames = {'potential_prox', 'smooth_potential'};
tableNames = {'prox', 'smooth'};
timeBudget = 900;
records = data.records;

assert(isequal(data.signature.sigma_list, sigmaList) ...
    && data.signature.epsilon == 1e-2 ...
    && data.signature.L == 32 && data.signature.N == 4096 ...
    && data.signature.beta == 10 && data.signature.delta == 10 ...
    && data.signature.pg_tolerance == 1e-6 ...
    && data.signature.time_limit == timeBudget, ...
    'The archive metadata do not match the paper experiment.');
assert(isequal(data.signature.splitting_list, splittingNames), ...
    'The archived splitting order is incompatible.');
assert(isequal(size(records), [numel(sigmaList), numel(splittingNames)]), ...
    'The archive does not contain exactly four trajectories.');

% The run script stores one common rho0 and constructs every run from it.
assert(isvector(data.rho0) && numel(data.rho0) == data.signature.N ...
    && all(isfinite(data.rho0)), 'The common initial state is invalid.');

checkpoint = load(data.checkpointFile, 'checkpoint');
assert(isfield(checkpoint, 'checkpoint') ...
    && isequaln(checkpoint.checkpoint.signature, data.signature), ...
    'The raw-run checkpoint is missing or has incompatible provenance.');
assert(isequal(size(checkpoint.checkpoint.runs), size(records)), ...
    'The raw-run checkpoint has an incompatible layout.');

commonSolverFields = {'a', 'L0', 'backtrack_factor', 'max_backtracks', ...
    'feasibility_tol', 'residual_step', 'residual_check_interval', ...
    'pg_tol', 'final_pg_tol', 'projection_name', 'time_limit', 'max_iter'};
referenceSolver = checkpoint.checkpoint.runs{1, 1}.solver;
referenceProblem = checkpoint.checkpoint.runs{1, 1}.problem;
assert(abs(src.constraints.Mass(data.rho0, referenceProblem.grid.h) ...
    - data.signature.mass) <= 1e-12, ...
    'The archived common initial state does not have the target mass.');
crossingTimes = nan(numel(sigmaList), numel(splittingNames), ...
    numel(thresholds));
crossingIterations = nan(size(crossingTimes));

for sigmaIndex = 1:numel(sigmaList)
    check = data.objectiveChecks(sigmaIndex);
    assert(check.sigma == sigmaList(sigmaIndex) ...
        && check.energy_reconstruction_difference <= 1e-12 ...
        && check.full_gradient_infinity_difference <= 1e-12, ...
        'Same-objective validation failed for sigma %.0e.', ...
        sigmaList(sigmaIndex));

    for splittingIndex = 1:numel(splittingNames)
        record = records(sigmaIndex, splittingIndex);
        raw = checkpoint.checkpoint.runs{sigmaIndex, splittingIndex};
        assert(record.sigma == sigmaList(sigmaIndex) ...
            && strcmp(record.splitting, splittingNames{splittingIndex}), ...
            'Trajectory metadata are out of order.');
        assert(numel(record.time) == numel(record.pg) ...
            && numel(record.time) == numel(record.iteration), ...
            'PG, time, and iteration histories have different lengths.');
        assert(record.time(1) == 0 && record.iteration(1) == 0 ...
            && all(diff(record.time) >= 0) ...
            && all(diff(record.iteration) == 1), ...
            'The trajectory history is not monotonically ordered.');
        assert(record.time(end) <= record.final_time ...
            && record.final_time == raw.diagnostics.main_elapsed_time, ...
            'The canonical timing source is inconsistent.');
        assert(strcmp(raw.solver.splitting, splittingNames{splittingIndex}), ...
            'Raw solver splitting metadata are incompatible.');
        for fieldIndex = 1:numel(commonSolverFields)
            field = commonSolverFields{fieldIndex};
            assert(isequaln(raw.solver.(field), referenceSolver.(field)), ...
                'Solver setting "%s" differs across trajectories.', field);
        end

        % Exclude index zero: crossing times must correspond to accepted
        % FISTA iterates, not the supplied initial density.
        acceptedPg = record.pg(2:end);
        acceptedTime = record.time(2:end);
        acceptedIteration = record.iteration(2:end);
        for thresholdIndex = 1:numel(thresholds)
            first = find(acceptedPg <= thresholds(thresholdIndex), 1, 'first');
            if ~isempty(first)
                crossingTimes(sigmaIndex, splittingIndex, thresholdIndex) = ...
                    acceptedTime(first);
                crossingIterations(sigmaIndex, splittingIndex, thresholdIndex) = ...
                    acceptedIteration(first);
                assert(all(acceptedPg(1:first - 1) ...
                    > thresholds(thresholdIndex)), ...
                    'A reported crossing is not the first accepted iterate.');
            else
                assert(strcmp(record.termination_reason, 'time_limit') ...
                    && record.final_time >= timeBudget, ...
                    'A missing crossing is not certified by the time budget.');
            end
        end

        finiteTimes = squeeze(crossingTimes( ...
            sigmaIndex, splittingIndex, :));
        finiteTimes = finiteTimes(isfinite(finiteTimes));
        assert(all(diff(finiteTimes) >= 0), ...
            'Time-to-target values violate threshold ordering.');
    end

    initialEnergyDifference = abs(records(sigmaIndex, 1).energy(1) ...
        - records(sigmaIndex, 2).energy(1));
    initialPgDifference = abs(records(sigmaIndex, 1).pg(1) ...
        - records(sigmaIndex, 2).pg(1));
    assert(initialEnergyDifference <= 10 * eps(max(1, abs( ...
        records(sigmaIndex, 1).energy(1)))) ...
        && initialPgDifference <= 10 * eps(max(1, abs( ...
        records(sigmaIndex, 1).pg(1)))), ...
        'The two splittings do not share the same initial state metrics.');
end

writeRows(rowsFile, sigmaList, tableNames, crossingTimes, timeBudget);
writeTableSnippet(tableFile, sigmaList, tableNames, crossingTimes, ...
    timeBudget);
writeCsv(csvFile, sigmaList, tableNames, records, crossingTimes, ...
    timeBudget);

fprintf('\nPotential-splitting time-to-stationarity\n');
fprintf('sigma method  T(1e-4) T(1e-5) T(1e-6)\n');
for sigmaIndex = 1:numel(sigmaList)
    for splittingIndex = 1:numel(tableNames)
        fprintf('%.0e %-6s', sigmaList(sigmaIndex), ...
            tableNames{splittingIndex});
        for thresholdIndex = 1:numel(thresholds)
            fprintf(' %9s', displayTime(crossingTimes( ...
                sigmaIndex, splittingIndex, thresholdIndex), timeBudget));
        end
        fprintf('\n');
    end
end
fprintf('Rows : %s\n', rowsFile);
fprintf('Table: %s\n', tableFile);
fprintf('CSV  : %s\n', csvFile);

function writeRows(filename, sigmaList, names, times, budget)
file = fopen(filename, 'w');
cleanup = onCleanup(@() fclose(file));
assert(file >= 0, 'Could not open %s for writing.', filename);
writeRowBlock(file, sigmaList, names, times, budget);
end

function writeRowBlock(file, sigmaList, names, times, budget)
for sigmaIndex = 1:numel(sigmaList)
    exponent = round(log10(sigmaList(sigmaIndex)));
    for splittingIndex = 1:numel(names)
        fprintf(file, '$10^{%d}$ & %s', exponent, ...
            names{splittingIndex});
        for thresholdIndex = 1:size(times, 3)
            value = times(sigmaIndex, splittingIndex, thresholdIndex);
            if isfinite(value)
                fprintf(file, ' & %.2f', value);
            else
                fprintf(file, ' & $>%d$', budget);
            end
        end
        isLastRow = sigmaIndex == numel(sigmaList) ...
            && splittingIndex == numel(names);
        if isLastRow
            fprintf(file, '%s', ' \\');
        else
            fprintf(file, '%s\n', ' \\');
        end
    end
end
end

function writeTableSnippet(filename, sigmaList, names, times, budget)
file = fopen(filename, 'w');
cleanup = onCleanup(@() fclose(file));
assert(file >= 0, 'Could not open %s for writing.', filename);
fprintf(file, '%s\n', ...
    '\begin{table}[t]', ...
    '\centering', ...
    '\caption{', ...
    'Wall-clock time (s) required by the potential-proximal and', ...
    'smooth-potential FISTA splittings to reach prescribed values of', ...
    'the projected-gradient residual', ...
    '$\|\mathcal G_{\tau_r}(\rho)\|_h$.', ...
    '}', ...
    '\label{tab:potential-splitting-comparison}', ...
    '\begin{tabular}{ccccc}', ...
    '\toprule', ...
    '$\sig$ & splitting', ...
    '& $10^{-4}$ & $10^{-5}$ & $10^{-6}$ \\', ...
    '\midrule');
writeRowBlock(file, sigmaList, names, times, budget);
fprintf(file, '\n%s\n', ...
    '\bottomrule', ...
    '\end{tabular}', ...
    '\end{table}');
end

function writeCsv(filename, sigmaList, names, records, times, budget)
rowCount = numel(sigmaList) * numel(names);
sigma = nan(rowCount, 1);
splitting = strings(rowCount, 1);
timePg1em4 = strings(rowCount, 1);
timePg1em5 = strings(rowCount, 1);
timePg1em6 = strings(rowCount, 1);
terminationReason = strings(rowCount, 1);
finalTime = nan(rowCount, 1);
finalPg = nan(rowCount, 1);
row = 0;
for sigmaIndex = 1:numel(sigmaList)
    for splittingIndex = 1:numel(names)
        row = row + 1;
        sigma(row) = sigmaList(sigmaIndex);
        splitting(row) = names{splittingIndex};
        values = squeeze(times(sigmaIndex, splittingIndex, :));
        timePg1em4(row) = displayTime(values(1), budget);
        timePg1em5(row) = displayTime(values(2), budget);
        timePg1em6(row) = displayTime(values(3), budget);
        terminationReason(row) = ...
            records(sigmaIndex, splittingIndex).termination_reason;
        finalTime(row) = records(sigmaIndex, splittingIndex).final_time;
        finalPg(row) = records(sigmaIndex, splittingIndex).final_pg;
    end
end
summary = table(sigma, splitting, timePg1em4, timePg1em5, ...
    timePg1em6, terminationReason, finalTime, finalPg, ...
    'VariableNames', {'sigma', 'splitting', 'time_pg_1e-4', ...
    'time_pg_1e-5', 'time_pg_1e-6', 'termination_reason', ...
    'final_time', 'final_pg'});
writetable(summary, filename);
end

function text = displayTime(value, budget)
if isfinite(value)
    text = sprintf('%.2f', value);
else
    text = sprintf('>%d', budget);
end
end
